Mongo db integration and testing is done
biplovale/Riki pull request #1
Opened 2023-11-12 17:47 UTC by sgavin0813

I have migrated to MongoDb and unit tested my code.
It is working Okay.
Changes were made to Core.py classes Wiki and Page class

2023-11-12 21:37 UTC, biplovale commented on tests/singh-gavin-unittests/__pycache__/TestPageClass.cpython-311.pyc
This looks like pycache files. Should be removed.

2023-11-12 21:37 UTC, biplovale commented on tests/singh-gavin-unittests/__pycache__/TestWikiClass.cpython-311.pyc
This looks like pycache files. Should be removed.

2023-11-12 21:38 UTC, biplovale commented on wiki/__pycache__/DataAccessObject.cpython-311.pyc
This looks like pycache files. Should be removed.

2023-11-12 21:38 UTC, biplovale commented on wiki/__pycache__/__init__.cpython-311.pyc
This looks like pycache files. Should be removed.

2023-11-12 21:38 UTC, biplovale commented on wiki/__pycache__/core.cpython-311.pyc
This looks like pycache files. Should be removed.

2023-11-12 21:41 UTC, biplovale commented on wiki/core.py
> +    def split_raw(self):
Why is there two split_raw()? Do we now need the old one?

2023-11-12 21:42 UTC, biplovale commented on wiki/core.py
Let's keep the preexiting comments for process_meta()

2023-11-12 22:00 UTC, biplovale commented on wiki/core.py
> +                if tag:
Can you explain why is this if condition needed?

2023-11-12 22:02 UTC, biplovale commented on wiki/web/__pycache__/__init__.cpython-311.pyc
Cache files must be removed.

2023-11-12 22:02 UTC, biplovale commented on wiki/web/__pycache__/forms.cpython-311.pyc
Cache files must be removed.

2023-11-12 22:02 UTC, biplovale commented on wiki/web/__pycache__/routes.cpython-311.pyc
Cache files must be removed.

2023-11-12 22:02 UTC, biplovale commented on wiki/web/__pycache__/user.cpython-311.pyc
Cache files must be removed.

2023-11-12 22:16 UTC, biplovale commented on config.py
> +USER_DIR = '/Users/gavinsingh/Documents/Riki/user'
CONTENT_DIR and USER_DIR can be completely removed now.

2023-11-12 22:16 UTC, biplovale commented on config.py
> +connection_string = "mongodb+srv://sgavin0813:password_1234@atlascluster.qdshz9s.mongodb.net/"
Can you make this all Caps

2023-11-12 22:22 UTC, biplovale commented on wiki/core.py
> +        self.new = new
I dont think this is necessary. Why do you have this here?

2023-11-13 04:12 UTC, biplovale commented
> I have migrated to MongoDb and unit tested my code. It is working Okay. Changes were made to Core.py classes Wiki and Page class

2023-11-13 04:15 UTC, biplovale requested changes
Remove content folder
Remove pycache folder and include it in .gitignore

2023-11-13 19:53 UTC, sgavin0813 reviewed
Updated the .gitignore file to exclude cache files from the repository.
Removed previously cached files that were present in the repo to maintain cleanliness and manageability.

2023-11-18 20:01 UTC, biplovale approved these changes

2023-11-18 20:02 UTC, merged